language: ruby
script: "bundle exec rake"
cache: bundler
rvm:
  - 2.1
  - 2.0.0
  - 2.2
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.2
  - jruby
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
